package uz.toshmatov.currency.core.extensions

import androidx.annotation.DrawableRes
import uz.toshmatov.currency.core.utils.drawable

enum class CurrencyCode(
    val country: String,
    @DrawableRes val flag: Int
) {
    AED(country = "United Arab Emirates", flag = drawable.united_arab_emirates),
    AFN(country = "Afghanistan", flag = drawable.afghanistan),
    ALL(country = "Albania", flag = drawable.albania),
    AMD(country = "Armenia", flag = drawable.armenia),
    ANG(country = "Netherlands", flag = drawable.netherlands),
    AOA(country = "Angola", flag = drawable.angola),
    ARS(country = "Argentina", flag = drawable.argentina),
    AUD(country = "Australia", flag = drawable.australia),
    AZN(country = "Azerbaijan", flag = drawable.azerbaijan),
    BAM(country = "Bosnia and Herzegovina", flag = drawable.bosnia_and_herzegovina),
    BBD(country = "Barbados", flag = drawable.barbados),
    BDT(country = "Bangladesh", flag = drawable.bangladesh),
    BGN(country = "Bulgaria", flag = drawable.bulgaria),
    BHD(country = "Bahrain", flag = drawable.bahrain),
    BMD(country = "Bermuda", flag = drawable.bermuda),
    BOB(country = "Bolivia", flag = drawable.bolivia),
    BRL(country = "Brazil", flag = drawable.brazil),
    BSD(country = "Bahamas", flag = drawable.bahamas),
    BTN(country = "Bhutan", flag = drawable.bhutan),
    BWP(country = "Botswana", flag = drawable.botswana),
    BYN(country = "Belarus", flag = drawable.belarus),
    BZD(country = "Belize", flag = drawable.belize),
    CAD(country = "Canada", flag = drawable.canada),
    CDF(country = "Democratic Republic of Congo", flag = drawable.democratic_republic_of_congo),
    CHF(country = "Switzerland", flag = drawable.switzerland),
    CLF(country = "Chile (Unidad de Fomento)", flag = drawable.chile),
    CLP(country = "Chile", flag = drawable.chile),
    CNY(country = "China", flag = drawable.china),
    COP(country = "Colombia", flag = drawable.colombia),
    CRC(country = "Costa Rica", flag = drawable.costa_rica),
    CUC(country = "Cuba (Convertible Peso)", flag = drawable.cuba),
    CUP(country = "Cuba (Cuban Peso)", flag = drawable.cuba),
    CVE(country = "Cape Verde", flag = drawable.cape_verde),
    CZK(country = "Czech Republic", flag = drawable.czech_republic),
    DJF(country = "Djibouti", flag = drawable.djibouti),
    DKK(country = "Denmark", flag = drawable.denmark),
    DOP(country = "Dominican Republic", flag = drawable.dominican_republic),
    DZD(country = "Algeria", flag = drawable.algeria),
    EGP(country = "Egypt", flag = drawable.egypt),
    ERN(country = "Eritrea", flag = drawable.eritrea),
    ETB(country = "Ethiopia", flag = drawable.ethiopia),
    EUR(country = "European Union", flag = drawable.european_union),
    FJD(country = "Fiji", flag = drawable.fiji),
    FKP(country = "Falkland Islands", flag = drawable.falkland_islands),
    GBP(country = "United Kingdom", flag = drawable.united_kingdom),
    GEL(country = "Georgia", flag = drawable.georgia),
    GGP(country = "Guernsey", flag = drawable.guernsey),
    GHS(country = "Ghana", flag = drawable.ghana),
    GIP(country = "Gibraltar", flag = drawable.gibraltar),
    GMD(country = "Gambia", flag = drawable.gambia),
    GNF(country = "Guinea", flag = drawable.guinea),
    GTQ(country = "Guatemala", flag = drawable.guatemala),
    GYD(country = "Guyana", flag = drawable.guyana),
    HKD(country = "Hong Kong", flag = drawable.hong_kong),
    HNL(country = "Honduras", flag = drawable.honduras),
    HRK(country = "Croatia", flag = drawable.croatia),
    HTG(country = "Haiti", flag = drawable.haiti),
    HUF(country = "Hungary", flag = drawable.hungary),
    IDR(country = "Indonesia", flag = drawable.indonesia),
    ILS(country = "Israel", flag = drawable.israel),
    IMP(country = "Isle of Man", flag = drawable.isle_of_man),
    INR(country = "India", flag = drawable.india),
    IQD(country = "Iraq", flag = drawable.iraq),
    IRR(country = "Iran", flag = drawable.iran),
    ISK(country = "Iceland", flag = drawable.iceland),
    JEP(country = "Jersey", flag = drawable.jersey),
    JMD(country = "Jamaica", flag = drawable.jamaica),
    JOD(country = "Jordan", flag = drawable.jordan),
    JPY(country = "Japan", flag = drawable.japan),
    KES(country = "Kenya", flag = drawable.kenya),
    KGS(country = "Kyrgyzstan", flag = drawable.kyrgyzstan),
    KHR(country = "Cambodia", flag = drawable.cambodia),
    KMF(country = "Comoros", flag = drawable.comoros),
    KPW(country = "North Korea", flag = drawable.north_korea),
    KRW(country = "South Korea", flag = drawable.south_korea),
    KWD(country = "Kuwait", flag = drawable.kuwait),
    KZT(country = "Kazakhstan", flag = drawable.kazakhstan),
    LAK(country = "Laos", flag = drawable.laos),
    LBP(country = "Lebanon", flag = drawable.lebanon),
    LKR(country = "Sri Lanka", flag = drawable.sri_lanka),
    LRD(country = "Liberia", flag = drawable.liberia),
    LSL(country = "Lesotho", flag = drawable.lesotho),
    LTL(country = "Lithuania", flag = drawable.lithuania),
    LYD(country = "Libya", flag = drawable.libya),
    MAD(country = "Morocco", flag = drawable.morocco),
    MDL(country = "Moldova", flag = drawable.moldova),
    MGA(country = "Madagascar", flag = drawable.madagascar),
    MKD(country = "North Macedonia", flag = drawable.north_macedonia),
    MMK(country = "Myanmar", flag = drawable.myanmar),
    MNT(country = "Mongolia", flag = drawable.mongolia),
    MOP(country = "Macao", flag = drawable.macao),
    MRO(country = "Mauritania", flag = drawable.mauritania),
    MRU(country = "Mauritius", flag = drawable.mauritius),
    MUR(country = "Mauritius", flag = drawable.mauritius),
    MVR(country = "Maldives", flag = drawable.maldives),
    MWK(country = "Malawi", flag = drawable.malawi),
    MXN(country = "Mexico", flag = drawable.mexico),
    MYR(country = "Malaysia", flag = drawable.malaysia),
    MZN(country = "Mozambique", flag = drawable.mozambique),
    NAD(country = "Namibia", flag = drawable.namibia),
    NGN(country = "Nigeria", flag = drawable.nigeria),
    NIO(country = "Nicaragua", flag = drawable.nicaragua),
    NOK(country = "Norway", flag = drawable.norway),
    NPR(country = "Nepal", flag = drawable.nepal),
    NZD(country = "New Zealand", flag = drawable.new_zealand),
    OMR(country = "Oman", flag = drawable.oman),
    PAB(country = "Panama", flag = drawable.panama),
    PGK(country = "Papua New Guinea", flag = drawable.papua_new_guinea),
    PHP(country = "Philippines", flag = drawable.philippines),
    PKR(country = "Pakistan", flag = drawable.pakistan),
    PLN(country = "Poland", flag = drawable.poland),
    PYG(country = "Paraguay", flag = drawable.paraguay),
    QAR(country = "Qatar", flag = drawable.qatar),
    RON(country = "Romania", flag = drawable.romania),
    RSD(country = "Serbia", flag = drawable.serbia),
    RUB(country = "Russia", flag = drawable.russia),
    RWF(country = "Rwanda", flag = drawable.rwanda),
    SAR(country = "Saudi Arabia", flag = drawable.saudi_arabia),
    SBD(country = "Solomon Islands", flag = drawable.solomon_islands),
    SCR(country = "Seychelles", flag = drawable.seychelles),
    SDG(country = "Sudan", flag = drawable.sudan),
    SEK(country = "Sweden", flag = drawable.sweden),
    SGD(country = "Singapore", flag = drawable.singapore),
    SLL(country = "Sierra Leone", flag = drawable.sierra_leone),
    SOS(country = "Somalia", flag = drawable.somalia),
    SRD(country = "Suriname", flag = drawable.suriname),
    STD(country = "São Tomé and Príncipe", flag = drawable.sao_tome_and_prince),
    SVC(country = "El Salvador", flag = drawable.el_salvador),
    SYP(country = "Syria", flag = drawable.syria),
    THB(country = "Thailand", flag = drawable.thailand),
    TJS(country = "Tajikistan", flag = drawable.tajikistan),
    TMT(country = "Turkmenistan", flag = drawable.turkmenistan),
    TND(country = "Tunisia", flag = drawable.tunisia),
    TOP(country = "Tonga", flag = drawable.tonga),
    TRY(country = "Turkiye", flag = drawable.turkey),
    TTD(country = "Trinidad and Tobago", flag = drawable.trinidad_and_tobago),
    TWD(country = "Taiwan", flag = drawable.taiwan),
    TZS(country = "Tanzania", flag = drawable.tanzania),
    UAH(country = "Ukraine", flag = drawable.ukraine),
    USD(country = "United States of America", flag = drawable.united_states),
    UZS(country = "Uzbekistan", flag = drawable.uzbekista_n),
    VES(country = "Venezuela", flag = drawable.venezuela),
    VND(country = "Vietnam", flag = drawable.vietnam),
    VUV(country = "Vanuatu", flag = drawable.vanuatu),
    WST(country = "Samoa", flag = drawable.samoa),
    XAF(country = "Central African Republic", flag = drawable.central_african_republic),
    YER(country = "Yemen", flag = drawable.yemen),
    ZAR(country = "South Africa", flag = drawable.south_africa),
    ZMW(country = "Zambia", flag = drawable.zambia),
    ZWL(country = "Zimbabwe", flag = drawable.zimbabwe),
    BND(country = "Brunei", flag = drawable.brunei),
    UYU(country = "Uruguayo", flag = drawable.uruguay),
    XDR(country = "SDR", flag = drawable.ic_empty_flag)
}